version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5400:5432"
    volumes:
      - ./migrate_script.sh:/migrate/migrate_script.sh
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=postgres_db

  go-service:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
